name: Prettier

on:
  pull_request:

env:
  FILE_PATTERN: "**/*.{js,json}"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm setup
        run: |
          npm ci
          npm run prettier --write ${FILE_PATTERN}